/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home_Page.java
 *
 * Created on 25 Nov, 2012, 11:33:00 AM
 */

package project;

/**
 *
 * @author sanjana
 */
public class Home_Page extends javax.swing.JFrame {

    /** Creates new form Home_Page */
    public Home_Page() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PATIENT_LOGIN = new javax.swing.JButton();
        DOCTOR_LOGIN = new javax.swing.JButton();
        NURSE_LOGIN = new javax.swing.JButton();
        DEPARTMENT = new javax.swing.JButton();
        ABOUT_US = new javax.swing.JComboBox();
        CONTACT_US = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("  AMRITA HOSPITAL MANAGEMENT SYSTEM");

        PATIENT_LOGIN.setText("PATIENT LOGIN");
        PATIENT_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PATIENT_LOGINActionPerformed(evt);
            }
        });

        DOCTOR_LOGIN.setText("DOCTOR LOGIN");

        NURSE_LOGIN.setText("NURSE LOGIN");

        DEPARTMENT.setText("DEPARTMENTS");
        DEPARTMENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEPARTMENTActionPerformed(evt);
            }
        });

        ABOUT_US.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ABOUT US", "OUR MOTTO", "OUR INSPIRATION", "HISTORY", "GETTING HERE" }));
        ABOUT_US.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABOUT_USActionPerformed(evt);
            }
        });

        CONTACT_US.setText("CONTACT US");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CONTACT_US, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DEPARTMENT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DOCTOR_LOGIN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PATIENT_LOGIN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NURSE_LOGIN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(361, 361, 361)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(464, 464, 464))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ABOUT_US, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ABOUT_US, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(PATIENT_LOGIN)
                .addGap(38, 38, 38)
                .addComponent(DOCTOR_LOGIN)
                .addGap(37, 37, 37)
                .addComponent(NURSE_LOGIN)
                .addGap(42, 42, 42)
                .addComponent(DEPARTMENT)
                .addGap(42, 42, 42)
                .addComponent(CONTACT_US)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ABOUT_USActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABOUT_USActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ABOUT_USActionPerformed

    private void DEPARTMENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEPARTMENTActionPerformed
        // TODO add your handling code here:
       Department Dep = new Department();
       Dep.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_DEPARTMENTActionPerformed

    private void PATIENT_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PATIENT_LOGINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PATIENT_LOGINActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ABOUT_US;
    private javax.swing.JButton CONTACT_US;
    private javax.swing.JButton DEPARTMENT;
    private javax.swing.JButton DOCTOR_LOGIN;
    private javax.swing.JButton NURSE_LOGIN;
    private javax.swing.JButton PATIENT_LOGIN;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
