/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Patient_Signup_Page.java
 *
 * Created on 25 Nov, 2012, 12:13:36 PM
 */

package project;
import java.sql.*;
import java.util.*;
/**
 *
 * @author sanjana
 */
public class Patient_Signup_Page extends javax.swing.JFrame {

    /** Creates new form Patient_Signup_Page */
    public Patient_Signup_Page() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Patient_signup_label = new javax.swing.JLabel();
        First_name_label = new javax.swing.JLabel();
        Last_Name_label = new javax.swing.JLabel();
        Age_label = new javax.swing.JLabel();
        Sex_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pf_name = new javax.swing.JTextField();
        pl_name = new javax.swing.JTextField();
        ur_age = new javax.swing.JTextField();
        ur_sex = new javax.swing.JComboBox();
        b_g = new javax.swing.JComboBox();
        m_s = new javax.swing.JComboBox();
        addr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        p_no = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c_pass = new javax.swing.JTextField();
        sign_but = new javax.swing.JButton();
        back_but = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        e_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Patient_signup_label.setText("                      PATIENT'S SIGN UP");

        First_name_label.setText("First Name        ");

        Last_Name_label.setText("Last Name       ");

        Age_label.setText("Age                          ");

        Sex_label.setText("Sex                          ");

        jLabel5.setText("Blood Group");

        jLabel6.setText("Marital Status");

        jLabel7.setText("Address");

        jLabel8.setText("Confirm Password");

        jLabel9.setText("Mobile No.");

        jLabel10.setText("Password");

        pf_name.setText("jTextField1");

        pl_name.setText("jTextField2");

        ur_age.setText("jTextField3");

        ur_sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        ur_sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ur_sexActionPerformed(evt);
            }
        });

        b_g.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));

        m_s.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married" }));

        addr.setText("jTextField4");

        jLabel1.setText("+91");

        p_no.setText("jTextField5");

        pass.setText("jTextField6");

        jLabel2.setText("minimum 8 characters");

        c_pass.setText("jTextField7");

        sign_but.setText("Sign in");
        sign_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_butActionPerformed(evt);
            }
        });

        back_but.setText("Back");

        jLabel3.setText("Email Id");

        e_id.setText("jTextField8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(First_name_label)
                    .addComponent(Last_Name_label)
                    .addComponent(Age_label)
                    .addComponent(Sex_label)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sign_but)
                        .addGap(136, 136, 136)
                        .addComponent(back_but)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ur_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ur_age, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pl_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p_no, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                                .addComponent(Patient_signup_label, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(e_id, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(c_pass, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(236, 236, 236))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Patient_signup_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(First_name_label)
                    .addComponent(pf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Last_Name_label)
                    .addComponent(pl_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age_label)
                    .addComponent(ur_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sex_label)
                    .addComponent(ur_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(b_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(m_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1)
                    .addComponent(p_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(c_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sign_but)
                    .addComponent(back_but, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ur_sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ur_sexActionPerformed
        // TODO add your handling code here:
        

//importing java packages

/**
 *
 * Authors : Nanditha Valsaraj        AM.EN.U4CSE10133
 *           Sanjana Reddy           AM.EN.U4CSE10147
 *           Sreepriya Chalakkal     AM.EN.U4CSE10153
 *
 */
        

    


    }//GEN-LAST:event_ur_sexActionPerformed

    private void sign_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_butActionPerformed
        // TODO add your handling code here:
        
         try{

                        String pid,pfname,plname,address,bg,email,gender,age;
                        int n=0;

                        /*pid=p_no.getText();
                        pfname=pf_name.getText();
                        plname=pl_name.getText();
                        address=addr.getText();
                       // bg=(String) b_g.getItemAt(0);
                        bg=(String) b_g.getSelectedItem();
                        email=e_id.getText();
                        //gender=(String) ur_sex.getItemAt(0);
                        gender=(String)ur_sex.getSelectedItem();
                        age=Integer.parseInt(ur_age.getText());*/
                        
                        Class.forName("org.postgresql.Driver");

                        Connection cn = DriverManager.getConnection("jdbc:postgresql://localhost/postgres","postgres","password");
                        
                        
                        /*String q1= "insert into patient values(?,?,?,?,?,?,?,?)";
                        pid=p_no.getText();
                        pfname=pf_name.getText();
                        plname=pl_name.getText();
                        address=addr.getText();
                        bg=(String) b_g.getSelectedItem();
                        email=e_id.getText();
                        gender=(String)ur_sex.getSelectedItem();
                        age=ur_age.getText();
                        PreparedStatement ps=cn.prepareStatement(q1);
                        ps.setString(1,pid);
                        ps.setString(2,pfname);
                        ps.setString(3,plname);
                        ps.setString(5,address);
                        ps.setString(4,bg);
                        ps.setString(6,email);
                        ps.setString(7,gender);
                        ps.setString(8,age);
                        System.out.println(plname );
                        ps.executeUpdate();*/
                        cn.close();
            }
            catch(Exception e)
            {
                        System.out.println("exception ="+ e);
            }
    }//GEN-LAST:event_sign_butActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_Signup_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age_label;
    private javax.swing.JLabel First_name_label;
    private javax.swing.JLabel Last_Name_label;
    private javax.swing.JLabel Patient_signup_label;
    private javax.swing.JLabel Sex_label;
    private javax.swing.JTextField addr;
    private javax.swing.JComboBox b_g;
    private javax.swing.JButton back_but;
    private javax.swing.JTextField c_pass;
    private javax.swing.JTextField e_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox m_s;
    private javax.swing.JTextField p_no;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField pf_name;
    private javax.swing.JTextField pl_name;
    private javax.swing.JButton sign_but;
    private javax.swing.JTextField ur_age;
    private javax.swing.JComboBox ur_sex;
    // End of variables declaration//GEN-END:variables

}
